Repository SOPT-32ND-APP4-Karrot/Carrot_iOS, pull requests merged in 2023-05, with the labels that each got.

#7 [#5] headerView 구현
  .gitignore
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Base/Header/HeaderView.swift
Labels: 🪦 채은, PR

#11 [#10] UILabel+ setting
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UILabel+.swift
Labels: 🪦 채은, PR, Chore

#9 [#8] Chat Header UI
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Base/Header/HeaderView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatHeader.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리@3x.png
Labels: 🪦 채은, UI, Feat, PR

#14 [#13] SaleHeaderView 구현
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/SaleHeaderView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/e.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리 1.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리@2x 1.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/다이어리.imageset/다이어리@3x 1.png
Labels: 💒 윤빈, UI, PR

#19 [#12] ChatTableView cell UI 구현
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatGuideTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatReceiveTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatSendTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/GuideView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ReceiveView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/SendView.swift
Labels: 🪦 채은, Feat, PR

#23 [#18] Navigation Bar 구현 (UIView로)
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.xcworkspace/xcuserdata/kyun.xcuserdatad/UserInterfaceState.xcuserstate
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/xcuserdata/kyun.xcuserdatad/xcschemes/xcschememanagement.plist
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIFont+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIStackView+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeHeaderView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/ViewController.swift
Labels: 👑 창균, UI, Feat, PR

#26 Feat [#22] SaleSecondSection UI 구성 완료
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Application/SceneDelegate.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIButton+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/DealTipView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/SaleDummyTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/SaleSecondSectionCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/ViewController/SaleViewController.swift
Labels: 💒 윤빈, UI, Feat, PR

#25 Feat [#20] chat input view
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UITextField+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIView+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIViewController+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatInputView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatViewController.swift
Labels: 🪦 채은, PR

#31 Network/#30 base url 등록
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Network/Config.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Network/NetworkResult.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Info.plist
Labels: 🪦 채은, PR

#33 Feat [#27] SaleThirdSection UI 구성 완료
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/SaleThirdSectionCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/ViewController/SaleViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_adImage.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_adImage.imageset/Rectangle 18.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_adImage.imageset/Rectangle 18@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_adImage.imageset/Rectangle 18@3x.png
Labels: 💒 윤빈, UI, Feat, PR

#35 Network [#29] Chat API 연결
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/String+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UIImageView+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Data/Chat/Chat.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Network/Chat/ChatService.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatHeader.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatInputView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/GuideView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ReceiveView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/SendView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/chat_ic_send_orange.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/chat_ic_send_orange.imageset/chat_ic_send@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/chat_ic_send_orange.imageset/chat_ic_send@3x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/chat_ic_send_orange.imageset/chat_ic_send_orange.png
Labels: 🪦 채은, PR

#38 Feat [#37] send button 로직 추가
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatInputView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ChatViewController.swift
Labels: 🪦 채은, PR

#40 Feat [#39] review VC UI 구현
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/Cell/ChatGuideTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/Cell/ChatReceiveTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/Cell/ChatSendTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/View/ChatHeader.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/View/ChatInputView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/View/GuideView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/View/ReceiveView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/View/SendView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Chat/ViewController/ChatViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Review/ReviewView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Review/ReviewViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_receive_image.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_receive_image.imageset/Rectangle 32.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_receive_image.imageset/Rectangle 32@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_receive_image.imageset/Rectangle 32@3x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_send_image.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_send_image.imageset/Rectangle 38.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_send_image.imageset/Rectangle 38@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/review_send_image.imageset/Rectangle 38@3x.png
Labels: 🪦 채은, UI, PR

#32 [#28] 홈 테이블 뷰 구현하기
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.xcworkspace/xcuserdata/kyun.xcuserdatad/UserInterfaceState.xcuserstate
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/xcuserdata/kyun.xcuserdatad/xcschemes/xcschememanagement.plist
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Application/SceneDelegate.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/NSObject+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Extensions/UITableView+.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Data/Home/HomeDataModel.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Data/Home/l.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/CarrotTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeNavigationView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_ic_downdown.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_ic_downdown.imageset/Group 33@1x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_ic_downdown.imageset/Group 33@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_ic_downdown.imageset/Group 33@3x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_img_advertising.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_img_advertising.imageset/advertisingImage@1x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_img_advertising.imageset/advertisingImage@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/home_img_advertising.imageset/advertisingImage@3x.png
Labels: 👑 창균, UI, Feat, PR

#43 Feat #34 SaleSalerSection 구성 완료
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Common/Consts/Image.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/SaleProductTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/View/SalerProductCollectionViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Sale/ViewController/SaleViewController.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_saler_product.imageset/Contents.json
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_saler_product.imageset/Rectangle 19.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_saler_product.imageset/Rectangle 19@2x.png
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Resource/Assets.xcassets/sale_ic_saler_product.imageset/Rectangle 19@3x.png
Labels: 💒 윤빈, UI, Feat, PR

#42 [Network] 홈뷰 서버통신
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.pbxproj
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS.xcodeproj/project.xcworkspace/xcuserdata/kyun.xcuserdatad/UserInterfaceState.xcuserstate
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Data/Home/HomeDataModel.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Network/Home/HomeService.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Network/Home/h.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeHeaderView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeNavigationView.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeTableViewCell.swift
  SOPT-32nd-APP4-CarrotiOS/SOPT-32nd-APP4-CarrotiOS/Presentation/Home/HomeViewController.swift
Labels: 👑 창균, PR, Network
